import java.util.*;  

class GuessNumber {
    int num;

    // Constructor to generate random number
    public GuessNumber() {
        Random rand = new Random();   // java.util.Random
        num = rand.nextInt(10);      // generates number between 0–99
    }

    void play() {
        Scanner sc = new Scanner(System.in);
        System.out.print("Guess the number between 0 to 100: ");
        int userInput = sc.nextInt(10);

        if (userInput == num) {
            System.out.println(" Congratulations! You guessed the correct number.");
        } else {
            System.out.println(" Sorry! The correct number was: " + num);
        }
    }

    public static void main(String[] args) {
        GuessNumber game = new GuessNumber();  // random number generated by constructor
        game.play();                            // play once
    }
}
